<?php

namespace anvildev\craftkickback\mcp;

use anvildev\craftkickback\elements\CommissionElement;
use anvildev\craftkickback\mcp\support\Presenter;
use Mcp\Capability\Attribute\McpTool;
use stimmt\craft\Mcp\attributes\McpToolMeta;
use stimmt\craft\Mcp\enums\ToolCategory;

/**
 * MCP tools for reading Kickback commissions (the earnings generated by a
 * referral, including MLM tiers). Read-only — approving, rejecting and reversing
 * commissions move money and run through the Control Panel.
 */
class CommissionTools
{
    use ToolResponseTrait;

    /**
     * @param int|null $affiliateId Filter by affiliate.
     * @param int|null $referralId Filter by referral.
     * @param string|null $status One of: pending, approved, paid, reversed, rejected.
     * @param int|null $payoutId Filter by the payout they were paid in.
     * @return array<string, mixed>
     */
    #[McpTool(
        name: 'kickback_list_commissions',
        description: 'List Kickback commissions, optionally filtered by affiliate, referral, status and payout.',
    )]
    #[McpToolMeta(category: ToolCategory::PLUGIN)]
    public function listCommissions(
        ?int $affiliateId = null,
        ?int $referralId = null,
        ?string $status = null,
        ?int $payoutId = null,
        int $limit = 50,
        int $offset = 0,
    ): array {
        return $this->guard(function() use ($affiliateId, $referralId, $status, $payoutId, $limit, $offset): array {
            $query = CommissionElement::find()
                ->siteId('*')
                ->status(null)
                ->limit($this->clampLimit($limit))
                ->offset($this->clampOffset($offset));
            if ($affiliateId !== null) {
                $query->affiliateId($affiliateId);
            }
            if ($referralId !== null) {
                $query->referralId($referralId);
            }
            if ($status !== null) {
                $query->commissionStatus($status);
            }
            if ($payoutId !== null) {
                $query->payoutId($payoutId);
            }
            $commissions = $query->all();

            return [
                'count' => count($commissions),
                'commissions' => array_map(static fn(CommissionElement $c) => Presenter::commission($c), $commissions),
            ];
        });
    }

    /**
     * @return array<string, mixed>
     */
    #[McpTool(
        name: 'kickback_get_commission',
        description: 'Get a single Kickback commission by id.',
    )]
    #[McpToolMeta(category: ToolCategory::PLUGIN)]
    public function getCommission(int $id): array
    {
        return $this->guard(function() use ($id): array {
            $commission = CommissionElement::find()->siteId('*')->status(null)->id($id)->one();
            if (!$commission instanceof CommissionElement) {
                return ['error' => "Commission #{$id} not found."];
            }

            return ['commission' => Presenter::commission($commission)];
        });
    }
}
