<?php

declare(strict_types=1);

namespace anvildev\craftkickback\gql\arguments\elements;

use craft\gql\base\ElementArguments;
use GraphQL\Type\Definition\Type;

class CommissionArguments extends ElementArguments
{
    public static function getArguments(): array
    {
        return array_merge(parent::getArguments(), [
            'affiliateId' => [
                'name' => 'affiliateId',
                'type' => Type::int(),
                'description' => 'Narrows results to commissions belonging to the given affiliate ID.',
            ],
            'commissionStatus' => [
                'name' => 'commissionStatus',
                'type' => Type::string(),
                'description' => 'Narrows results by commission status (pending, approved, paid, reversed, or rejected).',
            ],
            'referralId' => [
                'name' => 'referralId',
                'type' => Type::int(),
                'description' => 'Narrows results to commissions generated by the given referral ID.',
            ],
        ]);
    }
}
